# Generated by Django 5.1.4 on 2025-02-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('addr', models.CharField(max_length=64)),
                ('phno', models.IntegerField()),
                ('department', models.CharField(max_length=64)),
            ],
        ),
    ]
